# Generated by Django 6.1.1 on 2026-10-01 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sonido', models.CharField(choices=[('golpe', 'Golpe'), ('puerta', 'Puerta'), ('alarma', 'Alarma'), ('aplausos', 'Aplausos'), ('vidrio', 'Vidrio'), ('ruido_elevado', 'Ruido elevado'), ('desconocido', 'Desconocido')], max_length=30)),
                ('confianza', models.FloatField(help_text='Confianza del modelo entre 0 y 1.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='bajo', max_length=10)),
                ('duracion_segundos', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('origen', models.CharField(default='microfono', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detección',
                'verbose_name_plural': 'Detecciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
