# Generated by Django 6.1.1 on 2026-10-01 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detecciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deteccion',
            name='confianza',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='deteccion',
            name='tipo_sonido',
            field=models.CharField(choices=[('golpe', 'Golpe'), ('puerta', 'Puerta'), ('alarma', 'Alarma'), ('aplausos', 'Aplausos'), ('vidrio', 'Vidrio roto'), ('ruido_elevado', 'Ruido elevado'), ('desconocido', 'Desconocido')], default='desconocido', max_length=30),
        ),
    ]
