# Generated by Django 6.1.1 on 2026-10-03 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('golpe', 'Golpe'), ('puerta', 'Puerta'), ('alarma', 'Alarma'), ('aplausos', 'Aplausos'), ('vidrio', 'Vidrio'), ('ruido_elevado', 'Ruido elevado')], db_index=True, max_length=32)),
                ('origen', models.CharField(choices=[('archivo', 'Archivo'), ('microfono', 'Micrófono')], db_index=True, default='archivo', max_length=16)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo_relativo', models.CharField(max_length=500, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_audio_soundguard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
